apiVersion: apps/v1
kind: Deployment
metadata:
  name: testordermanagement
  labels:
    app: testordermanagement
spec:
  replicas: 4
  selector:
    matchLabels:
      app: testordermanagement
  template:
    metadata:
      labels:
        app: testordermanagement
    spec:
      containers:
        - name: testordermanagement
          image: skcc12acr.azurecr.io/testordermanagement:latest
          ports:
            - containerPort: 8080
          env:
            - name: configurl
              valueFrom:
                configMapKeyRef:
                  name: apiurl
                  key : url