apiVersion: v1
kind: Service
metadata:
  name: testordermanagement
  labels:
    app: testordermanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: testordermanagement
